# Clave del proyecto en SonarQube
sonar.projectKey=praxiuzdevelopment_backendDonPuntoQR

# Metadatos del proyecto
sonar.projectName=DonPunto QR Backend
sonar.projectVersion=1.0

# Fuentes a analizar
sonar.sources=src/

# Archivos o carpetas a excluir del análisis
sonar.exclusions=node_modules/**, docs/**, test/**, coverage/**, src/config/**

# Codificación
sonar.sourceEncoding=UTF-8

# Archivos o carpetas a excluir de detección de duplicados
sonar.cpd.exclusions=migrations/**, src/models/**

# Archivos de pruebas (Comentado hasta configurar Jest)
# sonar.tests=tests/
# sonar.javascript.lcov.reportPaths=coverage/lcov.info
